### ISSUE TITLE
Activate more gcc/clang warnings

### ISSUE THREAD

**Issue by minad** [jibsen/tinf#3]
I compile tinf with the following flags and get many warnings due to implicit casts (-Wconversion and -Wsign-conversion).
~~~
gcc -Isrc -Wall -Wextra -Wconversion -Wsign-conversion test/test_tinf.c src/*.c
~~~

**Comment by minad** [comment]
For reference, I reworked tinf_uncompress slightly for my vendoring in my project. See https://gist.github.com/minad/274787aaae0211d27afe6435e229b338. I applied the aforementioned changes in the types and I think the readability is not too bad. The test suite passes but I didn't run benchmarks.
If you are interested, I can prepare a patch upstreaming my changes (modulo the reformatting/renaming...).

**Comment by jibsen** [comment]
I am glad to hear you found a solution that works for your project. Thank you for the suggestions and link to your changes.

> Use precise types, e.g. uint32_t for crc32, size_t for buffer sizes etc. For return types I suggest using the precise tinf_error enum typedef.

The plan is to keep tinf 1.x c89 compatible. I have some changes I want to make to the interface for 2.x which might include moving to c99.

**Comment by minad** [comment]
It works well for now and I can merge back changes you make to tinf, which should be easy due to the great clarity of your code! Thank you for that :+1:

It would still be preferable to use the upstream version instead of a fork if possible. Moving to C99 would be very much appreciated!
